id: 592f9fbd6a2540ecaf698fcffc5e8c24
initial_creation_type: ocr
source_metadata:
  volumes:
    2d6a84fda42d4e4da6e72baca32e2738:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: གཤིན་རྗེ་གཤེད་པོ་སྒྲུབ་པའི་ཐབས།
      total_pages: 1044
      volume_number: 38
